In [1]:
import pandas as pd

In [22]:
df = pd.read_csv('ACS_16_5YR_S0601.csv')
df.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_EST_VC01,HC01_MOE_VC01,HC02_EST_VC01,HC02_MOE_VC01,HC03_EST_VC01,HC03_MOE_VC01,HC04_EST_VC01,...,HC04_EST_VC72,HC04_MOE_VC72,HC01_EST_VC73,HC01_MOE_VC73,HC02_EST_VC73,HC02_MOE_VC73,HC03_EST_VC73,HC03_MOE_VC73,HC04_EST_VC73,HC04_MOE_VC73
0,Id,Id2,Geography,Total; Estimate; Total population,Total; Margin of Error; Total population,Native; born in state of residence; Estimate; ...,Native; born in state of residence; Margin of ...,Native; born in other state in the U.S.; Estim...,Native; born in other state in the U.S.; Margi...,Native; born outside U.S.; Estimate; Total pop...,...,Native; born outside U.S.; Estimate; PERCENT A...,Native; born outside U.S.; Margin of Error; PE...,Total; Estimate; PERCENT ALLOCATED - Place of ...,Total; Margin of Error; PERCENT ALLOCATED - Pl...,Native; born in state of residence; Estimate; ...,Native; born in state of residence; Margin of ...,Native; born in other state in the U.S.; Estim...,Native; born in other state in the U.S.; Margi...,Native; born outside U.S.; Estimate; PERCENT A...,Native; born outside U.S.; Margin of Error; PE...
1,1400000US36061000100,36061000100,"Census Tract 1, New York County, New York",0,11,0,11,0,11,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1400000US36061000201,36061000201,"Census Tract 2.01, New York County, New York",2670,351,1092,218,282,140,199,...,NaN,NaN,9.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1400000US36061000202,36061000202,"Census Tract 2.02, New York County, New York",8016,564,4522,589,418,173,782,...,NaN,NaN,8.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1400000US36061000500,36061000500,"Census Tract 5, New York County, New York",0,11,0,11,0,11,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.columns = df.iloc[0,:]
df = df.iloc[1:,:]
df = df.reset_index(drop=True)
df.head()

,Id,Id2,Geography,Total; Estimate; Total population,Total; Margin of Error; Total population,Native; born in state of residence; Estimate; Total population,Native; born in state of residence; Margin of Error; Total population,Native; born in other state in the U.S.; Estimate; Total population,Native; born in other state in the U.S.; Margin of Error; Total population,Native; born outside U.S.; Estimate; Total population,...,Native; born outside U.S.; Estimate; PERCENT ALLOCATED - Citizenship status,Native; born outside U.S.; Margin of Error; PERCENT ALLOCATED - Citizenship status,Total; Estimate; PERCENT ALLOCATED - Place of birth,Total; Margin of Error; PERCENT ALLOCATED - Place of birth,Native; born in state of residence; Estimate; PERCENT ALLOCATED - Place of birth,Native; born in state of residence; Margin of Error; PERCENT ALLOCATED - Place of birth,Native; born in other state in the U.S.; Estimate; PERCENT ALLOCATED - Place of birth,Native; born in other state in the U.S.; Margin of Error; PERCENT ALLOCATED - Place of birth,Native; born outside U.S.; Estimate; PERCENT ALLOCATED - Place of birth,Native; born outside U.S.; Margin of Error; PERCENT ALLOCATED - Place of birth
0,1400000US36061000100,36061000100,"Census Tract 1, New York County, New York",0,11,0,11,0,11,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1400000US36061000201,36061000201,"Census Tract 2.01, New York County, New York",2670,351,1092,218,282,140,199,...,NaN,NaN,9.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1400000US36061000202,36061000202,"Census Tract 2.02, New York County, New York",8016,564,4522,589,418,173,782,...,NaN,NaN,8.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1400000US36061000500,36061000500,"Census Tract 5, New York County, New York",0,11,0,11,0,11,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1400000US36061000600,36061000600,"Census Tract 6, New York County, New York",10765,1214,3902,928,813,461,390,...,NaN,NaN,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Clean Census tract

In [26]:
def cleanCensusTract(x):
    """Cleans 'Geography' column into Census tract"""
    
    x_split = x.split(',')
    x_split = x_split[0].split(' ')
    return x_split[2]

In [29]:
df['censusTract'] = df.Geography.apply(lambda x: cleanCensusTract(x))

In [30]:
df.censusTract.value_counts()

152       1
100       1
181       1
104       1
125       1
295       1
237       1
149       1
72        1
52        1
156.02    1
165       1
14.02     1
212       1
153       1
185       1
257       1
223.01    1
95        1
73        1
194       1
89        1
281       1
253       1
273       1
138       1
124       1
132       1
55.02     1
80        1
         ..
98        1
142       1
38        1
148.01    1
214       1
37        1
173       1
61        1
114.01    1
8         1
230       1
283       1
267       1
88        1
146.01    1
31        1
28        1
215       1
130       1
187       1
239       1
227       1
197.01    1
184       1
5         1
177       1
36.01     1
236       1
263       1
113       1
Name: censusTract, Length: 288, dtype: int64